refactor: Use lib/redux-cozy-client instead of cozy-client in imports
- Clearer to see that this is not a package from node_modules
- Removes config from webpack
- Fixes a bug from eslint loader that tries to find a package.json

```
    Error: ENOENT: no such file or directory, open '/code/cozy/home/src/lib/redux-cozy-client/package.json'
        at Object.openSync (fs.js:443:3)
        at Object.readFileSync (fs.js:343:35)
        at readFile (/code/cozy/home/node_modules/cozy-scripts/node_modules/eslint/lib/config/config-file.js:64:15)
```